### ISSUE TITLE
How to include in it component?

### ISSUE THREAD

**Issue by pRatikSathaye** [emberjs/ember-jquery#128]
I am trying to import **@ember/jquery** in my component.
I did install **@ember/jquery** and **@ember/optional-features** and imported as below
`import $ from '@ember/jquery'`
but I am getting error **missing module @ember/jquery** in my component.

Is this the right way to import it? Am I missing something?

**Comment by geetchoudhary** [comment]
@pRatikSathaye , Did you find the right way?

**Comment by chancancode** [comment]
`import $ from 'jquery';`
