### ISSUE TITLE
Check EmberCLI version?

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember-jquery#3]
Shouldn't we check the Ember CLI version to make sure it is at least the one that includes the changes in https://github.com/ember-cli/ember-cli/pull/7841?

This is to prevent importing jQuery twice (by this addon as well as Ember CLI itself). Was also mentioned in the RFC [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#add-an-opt-out-flag):

> The addon itself has to make sure the Ember CLI version in use is at least the one that introduced the above mentioned logic, to prevent importing jQuery twice.

Or do I miss sth? /cc @cibernox @rwjblue

**Comment by rwjblue** [comment]
Good catch, will work on it.

**Comment by rwjblue** [comment]
#4 should fix
