### ISSUE TITLE
Ember Global deprecation warnings

### ISSUE THREAD

**Issue by navels** [emberjs/ember-jquery#478]
I'm using Ember v3.28 and ember-jquery v2.0.0.  Loading this addon is triggering these warnings
> DEPRECATION: Usage of the Ember Global is deprecated.

due to this code in my compiled app:
```
(function () {
  /*
   * This non-standard use of `reopen` and `call` allows the component
   * base class to be reopened without triggering the
   * ember.component.reopen deprecation in Ember itself.
   */
  Ember.Object.reopen.call(Ember.Component, {
    $(sel) {
  ...
```

However . . . the source code on disk, in `node_modules/@ember/jquery/vendor/jquery/component.dollar.js` is
```
import { assert, deprecate } from '@ember/debug';
import EmberObject from '@ember/object';
import Component from '@ember/component';

(function() {
  /*
   * This non-standard use of `reopen` and `call` allows the component
   * base class to be reopened without triggering the
   * ember.component.reopen deprecation in Ember itself.
   */
  EmberObject.reopen.call(Component, {
    $(sel) {
...
```

Sigh . . . anyone know how/why the latter is resulting in the former?

**Comment by navels** [comment]
~Aha!  We had `ember-cli-babel` as a dev dependency instead of a regular dependency and as a result `babel-plugin-ember-modules-api-polyfill` was doing it's thang.~

That wasn't it. I asked about this in the ember discord and apparently here is a workaround:

https://github.com/discourse/discourse/blob/main/app/assets/javascripts/patches/%40ember%2Bjquery%2B2.0.0.patch

**Comment by dion-** [comment]
> ~Aha! We had `ember-cli-babel` as a dev dependency instead of a regular dependency and as a result `babel-plugin-ember-modules-api-polyfill` was doing it's thang.~
> 
> That wasn't it. I asked about this in the ember discord and apparently here is a workaround:
> 
> https://github.com/discourse/discourse/blob/main/app/assets/javascripts/patches/%40ember%2Bjquery%2B2.0.0.patch

Looks like this patch has since been removed and this link 404s now. 

Here is a working link in case anyone needs this:

Patch:
https://github.com/discourse/discourse/blob/c320c286f92cc610a27f853a37cdc276227c44b1/app/assets/javascripts/patches/%40ember%2Bjquery%2B2.0.0.patch

Commit:
https://github.com/discourse/discourse/commit/c320c286f92cc610a27f853a37cdc276227c44b1
