### ISSUE TITLE
security vulnerability detected in jquery < 3.4.0

### ISSUE THREAD

**Issue by mathieupoteriepeopledoc** [emberjs/ember-jquery#77]
Hi !

Some of my repos has received this warning from github.
`
Known moderate severity security vulnerability detected in jquery < 3.4.0 defined in yarn.lock. 
`

This warning comes from ember-jquery.
I saw some commits updating jQuery, but not released yet. Is there a release planned for the next days ? Do you need some help, pair, or anything to get this done ?

**Comment by patocallaghan** [comment]
@mathieupoteriepeopledoc if you're still waiting on a release you can run `yarn upgrade jquery` (or `npm update jquery`) to upgrade to the latest jQuery version.

**Comment by simonihmig** [comment]
Seems dependabot already updated this for us, but indeed this is not released. I don't have npm rights, so @rwjblue or any body else being an npm owner: can we publish a patch release?

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember-jquery/releases/tag/v0.6.1
