### ISSUE TITLE
Upgrade to jQuery 3.4.1

### ISSUE THREAD

**Issue by HerveSeger** [emberjs/ember-jquery#91]
Hi.

I just hit the error [`saved.shift is not a function'](https://github.com/jquery/jquery/issues/4350) in one of my tests in Chrome.

This is fixed in `jQuery v3.4.1` but `ember-jquery v0.6.0` embeds `jQuery v3.4.0`.

 I can see that the `master` branch is up-to-date with `jQuery v3.4.1` and I just installed the `master` version locally and it fixes the issue.

Could we get a new release of `ember-jquery` from the `master` branch please?

**Comment by simonihmig** [comment]
The jQuery dependency is not pinned to this exact version, rather `^3.4.0` will install the latest 3.x.x version, including 3.4.1. I suppose you have a lock file (`yarn.lock` or `package.lock`), that has locked that version!? 

Upgrading that (e.g. `yarn upgrade`) should give you the latest version!

Closing this as dependabot has already bumped that version in git. But I don't think we will publish a release for every dependency bump unless there is a good reason!?

**Comment by simonihmig** [comment]
> But I don't think we will publish a release for every dependency bump unless there is a good reason!?

Oh, seems I was a bit too quick to rule out a new release, as there is this security alert (see https://github.com/emberjs/ember-jquery/issues/77), so we should probably do a release indeed!?

I am a member only on github, not npm, so cannot do this. Anyone with npm rights able to publish a patch release? Or `npm owner add simonihmig @ember/jquery` /cc @rwjblue
